### YamlMime:ManagedReference
items:
- uid: Ddap.Core.IIndexConfiguration
  commentId: T:Ddap.Core.IIndexConfiguration
  id: IIndexConfiguration
  parent: Ddap.Core
  children:
  - Ddap.Core.IIndexConfiguration.IndexName
  - Ddap.Core.IIndexConfiguration.IsClustered
  - Ddap.Core.IIndexConfiguration.IsUnique
  - Ddap.Core.IIndexConfiguration.PropertyNames
  langs:
  - csharp
  - vb
  name: IIndexConfiguration
  nameWithType: IIndexConfiguration
  fullName: Ddap.Core.IIndexConfiguration
  type: Interface
  source:
    remote:
      path: src/Ddap.Core/IIndexConfiguration.cs
      branch: copilot/fix-documentation-build-errors
      repo: https://github.com/schivei/ddap
    id: IIndexConfiguration
    path: ../src/Ddap.Core/IIndexConfiguration.cs
    startLine: 5
  assemblies:
  - Ddap.Core
  namespace: Ddap.Core
  summary: Represents the configuration for an index on an entity.
  example: []
  syntax:
    content: public interface IIndexConfiguration
    content.vb: Public Interface IIndexConfiguration
- uid: Ddap.Core.IIndexConfiguration.IndexName
  commentId: P:Ddap.Core.IIndexConfiguration.IndexName
  id: IndexName
  parent: Ddap.Core.IIndexConfiguration
  langs:
  - csharp
  - vb
  name: IndexName
  nameWithType: IIndexConfiguration.IndexName
  fullName: Ddap.Core.IIndexConfiguration.IndexName
  type: Property
  source:
    remote:
      path: src/Ddap.Core/IIndexConfiguration.cs
      branch: copilot/fix-documentation-build-errors
      repo: https://github.com/schivei/ddap
    id: IndexName
    path: ../src/Ddap.Core/IIndexConfiguration.cs
    startLine: 10
  assemblies:
  - Ddap.Core
  namespace: Ddap.Core
  summary: Gets the name of the index.
  example: []
  syntax:
    content: string IndexName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property IndexName As String
  overload: Ddap.Core.IIndexConfiguration.IndexName*
- uid: Ddap.Core.IIndexConfiguration.PropertyNames
  commentId: P:Ddap.Core.IIndexConfiguration.PropertyNames
  id: PropertyNames
  parent: Ddap.Core.IIndexConfiguration
  langs:
  - csharp
  - vb
  name: PropertyNames
  nameWithType: IIndexConfiguration.PropertyNames
  fullName: Ddap.Core.IIndexConfiguration.PropertyNames
  type: Property
  source:
    remote:
      path: src/Ddap.Core/IIndexConfiguration.cs
      branch: copilot/fix-documentation-build-errors
      repo: https://github.com/schivei/ddap
    id: PropertyNames
    path: ../src/Ddap.Core/IIndexConfiguration.cs
    startLine: 15
  assemblies:
  - Ddap.Core
  namespace: Ddap.Core
  summary: Gets the collection of property names included in the index.
  example: []
  syntax:
    content: IReadOnlyList<string> PropertyNames { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IReadOnlyList{System.String}
    content.vb: ReadOnly Property PropertyNames As IReadOnlyList(Of String)
  overload: Ddap.Core.IIndexConfiguration.PropertyNames*
- uid: Ddap.Core.IIndexConfiguration.IsUnique
  commentId: P:Ddap.Core.IIndexConfiguration.IsUnique
  id: IsUnique
  parent: Ddap.Core.IIndexConfiguration
  langs:
  - csharp
  - vb
  name: IsUnique
  nameWithType: IIndexConfiguration.IsUnique
  fullName: Ddap.Core.IIndexConfiguration.IsUnique
  type: Property
  source:
    remote:
      path: src/Ddap.Core/IIndexConfiguration.cs
      branch: copilot/fix-documentation-build-errors
      repo: https://github.com/schivei/ddap
    id: IsUnique
    path: ../src/Ddap.Core/IIndexConfiguration.cs
    startLine: 20
  assemblies:
  - Ddap.Core
  namespace: Ddap.Core
  summary: Gets a value indicating whether this is a unique index.
  example: []
  syntax:
    content: bool IsUnique { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property IsUnique As Boolean
  overload: Ddap.Core.IIndexConfiguration.IsUnique*
- uid: Ddap.Core.IIndexConfiguration.IsClustered
  commentId: P:Ddap.Core.IIndexConfiguration.IsClustered
  id: IsClustered
  parent: Ddap.Core.IIndexConfiguration
  langs:
  - csharp
  - vb
  name: IsClustered
  nameWithType: IIndexConfiguration.IsClustered
  fullName: Ddap.Core.IIndexConfiguration.IsClustered
  type: Property
  source:
    remote:
      path: src/Ddap.Core/IIndexConfiguration.cs
      branch: copilot/fix-documentation-build-errors
      repo: https://github.com/schivei/ddap
    id: IsClustered
    path: ../src/Ddap.Core/IIndexConfiguration.cs
    startLine: 25
  assemblies:
  - Ddap.Core
  namespace: Ddap.Core
  summary: Gets a value indicating whether this is a clustered index.
  example: []
  syntax:
    content: bool IsClustered { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property IsClustered As Boolean
  overload: Ddap.Core.IIndexConfiguration.IsClustered*
references:
- uid: Ddap.Core
  commentId: N:Ddap.Core
  href: Ddap.html
  name: Ddap.Core
  nameWithType: Ddap.Core
  fullName: Ddap.Core
  spec.csharp:
  - uid: Ddap
    name: Ddap
    href: Ddap.html
  - name: .
  - uid: Ddap.Core
    name: Core
    href: Ddap.Core.html
  spec.vb:
  - uid: Ddap
    name: Ddap
    href: Ddap.html
  - name: .
  - uid: Ddap.Core
    name: Core
    href: Ddap.Core.html
- uid: Ddap.Core.IIndexConfiguration.IndexName*
  commentId: Overload:Ddap.Core.IIndexConfiguration.IndexName
  href: Ddap.Core.IIndexConfiguration.html#Ddap_Core_IIndexConfiguration_IndexName
  name: IndexName
  nameWithType: IIndexConfiguration.IndexName
  fullName: Ddap.Core.IIndexConfiguration.IndexName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Ddap.Core.IIndexConfiguration.PropertyNames*
  commentId: Overload:Ddap.Core.IIndexConfiguration.PropertyNames
  href: Ddap.Core.IIndexConfiguration.html#Ddap_Core_IIndexConfiguration_PropertyNames
  name: PropertyNames
  nameWithType: IIndexConfiguration.PropertyNames
  fullName: Ddap.Core.IIndexConfiguration.PropertyNames
- uid: System.Collections.Generic.IReadOnlyList{System.String}
  commentId: T:System.Collections.Generic.IReadOnlyList{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IReadOnlyList`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<string>
  nameWithType: IReadOnlyList<string>
  fullName: System.Collections.Generic.IReadOnlyList<string>
  nameWithType.vb: IReadOnlyList(Of String)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of String)
  name.vb: IReadOnlyList(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.Collections.Generic.IReadOnlyList`1
  commentId: T:System.Collections.Generic.IReadOnlyList`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<T>
  nameWithType: IReadOnlyList<T>
  fullName: System.Collections.Generic.IReadOnlyList<T>
  nameWithType.vb: IReadOnlyList(Of T)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of T)
  name.vb: IReadOnlyList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Ddap.Core.IIndexConfiguration.IsUnique*
  commentId: Overload:Ddap.Core.IIndexConfiguration.IsUnique
  href: Ddap.Core.IIndexConfiguration.html#Ddap_Core_IIndexConfiguration_IsUnique
  name: IsUnique
  nameWithType: IIndexConfiguration.IsUnique
  fullName: Ddap.Core.IIndexConfiguration.IsUnique
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Ddap.Core.IIndexConfiguration.IsClustered*
  commentId: Overload:Ddap.Core.IIndexConfiguration.IsClustered
  href: Ddap.Core.IIndexConfiguration.html#Ddap_Core_IIndexConfiguration_IsClustered
  name: IsClustered
  nameWithType: IIndexConfiguration.IsClustered
  fullName: Ddap.Core.IIndexConfiguration.IsClustered
